<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MQLess\Module'                       => __DIR__ . '/Module.php',
  'MQLess\Exception\ExceptionInterface' => __DIR__ . '/src/MQLess/Exception/ExceptionInterface.php',
  'MQLess\Exception\RuntimeException'   => __DIR__ . '/src/MQLess/Exception/RuntimeException.php',
  'MQLess\View\Helper\Less'             => __DIR__ . '/src/MQLess/View/Helper/Less.php',
  'LessTest'                            => __DIR__ . '/tests/MQLess/View/Helper/LessTest.php',
);
