<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MQUtil\Module'                       => __DIR__ . '/Module.php',
  'MQUtil\Exception\ExceptionInterface' => __DIR__ . '/src/MQUtil/Exception/ExceptionInterface.php',
  'MQUtil\Exception\RuntimeException'   => __DIR__ . '/src/MQUtil/Exception/RuntimeException.php',
  'MQUtil\View\Helper\Less'             => __DIR__ . '/src/MQUtil/View/Helper/Less.php',
  'LessTest'                            => __DIR__ . '/tests/MQUtil/View/Helper/LessTest.php',
);
